config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :recipes, only: %i[ create show ]
  resources :user, only: %i[ destroy ]
  resources :sessions, only: %i[ create show ]

  get "signup", to: "users#signup"
  get "login", to: "sessions#login"
  get "logout", to: "sessions#logout"
  get "about", to: "about#index"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :url, presence: true
  validates :author, presence: true
  validates :recipe_name, presence: true
  validates :ingredients, presence: true
  validates :instructions, presence: true

  # we gotta fix whatever this is
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	validates :email, presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index;end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index;end
end

app/controllers/recipes_controller.rb
require "net/http"
require "uri"
require "json"

class RecipesController < ApplicationController
  def create
    recipe = Recipe.new(url: params[:recipe][:url])
    recipe.save

    response = RecipeService.get_recipe(params["recipe"]["url"])
    parse_response(response, recipe)

    redirect_to recipe_path(recipe.id)
  end

  def show
    @recipe = Recipe.find(params["id"])
    @instructions = JSON.parse(@recipe["instructions"])
    @ingredients = JSON.parse(@recipe["ingredients"])
  end

  private
  def parse_response(response, recipe)
    simplified_markdown = JSON.parse(response["converted"])

    recipe.markdown = response["original"]
    recipe.author = simplified_markdown["author"]
    recipe.recipe_name = simplified_markdown["recipe_name"]
    recipe.ingredients = simplified_markdown["ingredients"]
    recipe.instructions = simplified_markdown["instructions"]

    recipe.save
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def login
		@user = User.new
	end

	def create
		@user = User.find_by(email: params[:user][:email])

		if @user and @user.authenticate(params[:user][:password])
			session[:user_id] = @user.id
      		redirect_to root_path, flash: { success: 'Logged in successfully' }
		end
	end

	def logout
		session.delete(:user_id)

		redirect_to root_path, flash: { success: 'Logged out succesfully' }
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def signup;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def logged_in?()
		if session[:user_id]
			true
		else 
			false
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<h2>About Page</h2>

<p>
	Simple Crud app to store some recipes I like. Also act as rails skeleton for any future poject I need.
</p>

app/views/home/index.html.erb
<html>
  <head>
    <title>Simplify</title>
  </head>
  <body>
    <h1>Simplify</h1>
    <div>
      <%= form_with model: Recipe, url: recipes_path, method: :post, local: true do |f| %>
        <div>
          <%= f.label :url %><br>
          <%= f.text_field :url %>
        </div>

        <div>
          <%= f.submit "Submit" %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/_navbar.html.erb
<header>
	<div class="nav_container">
		<ul class="nav_items">
			<li><%= link_to "home", root_path %></li>
			<% if !logged_in? %>
				<li><%= link_to "login", login_path %></li>
				<li><%= link_to "sign up", signup_path %></li>
			<% end %>
			<li><%= link_to "about", about_path %></li>
			<% if logged_in? %>
				<li><%= link_to "my recipes", about_path %></li>
				<li><%= link_to "logout", logout_path %></li>
			<% end %>
		</ul>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Simplify" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipes/show.html.erb
<div class="center"><h1><%= @recipe.recipe_name %></h1></div>
<div class="center"><%= @recipe.author %></div>
<div class="center"><%= @recipe.url %></div>

<div class="flex-container">
  <div class="column">
    <h2 class="col-head">Ingredients</h2>
    <% @ingredients.each do |ingredient| %>
      <ul>
        <li><%= ingredient %></li>
      </ul>
    <% end %>
  </div>
  <div class="column">
    <h2 class="col-head">Instructions</h2>
    <% @instructions.each do |instruction| %>
      <ul>
        <li><%= instruction %></li>
      </ul>
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<h2>Sign Up Page</h2>
<div>
  <%= form_with model: User, url: sessions_path, method: :get, local: true do |f| %>
    <div>
      <%= f.label :email %><br>
      <%= f.text_field :email %><br>
      <%= f.label :password %><br>
      <%= f.password_field :password %><br>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %><br>
    </div>

    <div>
      <%= f.submit "Sign Up" %>
    </div>
  <% end %>
</div>